apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namePrefix: dev-

patches:
  - patch: |
      - op: replace
        path: /spec/template/spec/volumes/persistentVolumeClaim/0/claimName
        value: dev-base-vm-disk
      - op: replace
        path: /spec/template/spec/domain/memory/guest
        value: 4096M
    target:
      kind: VirtualMachine
